import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Providers from '@/providers';
import Main from '@/components/main';
import LoginModal from '@/components/modals/login-modal';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'TasteHorizon',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <LoginModal />

          <Main>{children}</Main>
        </Providers>
      </body>
    </html>
  );
}
